//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Utils.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are dublicate of category or wrong category Id.
        /// </summary>
        public static string CategoryConflictError {
            get {
                return ResourceManager.GetString("CategoryConflictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with this id not found.
        /// </summary>
        public static string CategoryIdNotFoundError {
            get {
                return ResourceManager.GetString("CategoryIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is not found.
        /// </summary>
        public static string CategoryNotFoundError {
            get {
                return ResourceManager.GetString("CategoryNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with this name already exists.
        /// </summary>
        public static string ExistingCategoryError {
            get {
                return ResourceManager.GetString("ExistingCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderItem is already exists.
        /// </summary>
        public static string ExistingOrderItemError {
            get {
                return ResourceManager.GetString("ExistingOrderItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with this data is already exist.
        /// </summary>
        public static string ExistingProductError {
            get {
                return ResourceManager.GetString("ExistingProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this phone number is already exists.
        /// </summary>
        public static string ExistingUserPhoneNumberError {
            get {
                return ResourceManager.GetString("ExistingUserPhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image upload failure.
        /// </summary>
        public static string ImageUploadFailureError {
            get {
                return ResourceManager.GetString("ImageUploadFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jwt settings not found.
        /// </summary>
        public static string JwtSettingsNotFoundError {
            get {
                return ResourceManager.GetString("JwtSettingsNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order with this Id not found.
        /// </summary>
        public static string OrderIdNotFoundError {
            get {
                return ResourceManager.GetString("OrderIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderItem data not found.
        /// </summary>
        public static string OrderItemDataNotFoundError {
            get {
                return ResourceManager.GetString("OrderItemDataNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with this Id not found.
        /// </summary>
        public static string OrderItemIdNotFoundError {
            get {
                return ResourceManager.GetString("OrderItemIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product creation failure.
        /// </summary>
        public static string ProductCreationFailureError {
            get {
                return ResourceManager.GetString("ProductCreationFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product deletion failure.
        /// </summary>
        public static string ProductDeletionFailureError {
            get {
                return ResourceManager.GetString("ProductDeletionFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with this Id not found.
        /// </summary>
        public static string ProductIdNotFound {
            get {
                return ResourceManager.GetString("ProductIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with this id is not found.
        /// </summary>
        public static string ProductIdNotFoundError {
            get {
                return ResourceManager.GetString("ProductIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product update failure.
        /// </summary>
        public static string ProductUpdateFailureError {
            get {
                return ResourceManager.GetString("ProductUpdateFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this id is not found.
        /// </summary>
        public static string UserIdNotFoundError {
            get {
                return ResourceManager.GetString("UserIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User phone number is not found.
        /// </summary>
        public static string UserPhoneNotFoundError {
            get {
                return ResourceManager.GetString("UserPhoneNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password is wrong.
        /// </summary>
        public static string WrongPasswordError {
            get {
                return ResourceManager.GetString("WrongPasswordError", resourceCulture);
            }
        }
    }
}
